accounts/urls.py
from django.urls import path
from .views import company_register, company_register_information, login, profile, update_company, change_password, logout, delete_account

app_name = 'accounts'
urlpatterns = [
    path('register/company/', company_register, name='company_register'),
    path('register/company_information/', company_register_information, name='company_register_information'),
    path('login/', login, name='login'),
    path('profile/<int:company_id>/', profile, name='company_detail'),
    path('update_company/<int:company_id>/', update_company, name='update_company'),
    path('password/change/', change_password, name='change_password'),
    path('logout/<int:company_id>/', logout, name='logout'),
    path('delete_account/<int:company_id>/', delete_account, name='delete_account')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls")),
    path('warehouse/', include("warehouse.urls")),
    path('supplier/', include("supplier.urls")),
    path('purchaseinvoice/', include("purchaseinvoice.urls")),
    path('product/', include("product.urls")),
    path('salesinvoice/', include("salesinvoice.urls")),
    path('customer/', include("customer.urls")),
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'
urlpatterns = [
    path('', home, name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from shared.validators import validate_numeric

# Create your models here.
class Company(models.Model):
    CATEGORY_CHOICE = [
        ("1", "موبایل"),
        ("2", "کتاب، لوازم تحریر و هنر"),
        ("3", "کالای دیجیتال"),
        ("4", "خانه و آشپزخانه"),
        ("5", "لوازم خانگی برقی"),
        ("6", "مد و پوشاک"),
        ("7", "ساعت، طلا و جواهرات"),
        ("8", "آرایشی بهداشتی"),
        ("9", "تجهیزات پزشکی و سلامت"),
        ("10", "ورزش و سفر"),
        ("11", "کارت هدیه و گیفت کارت"),
        ("12", "کالاهای سوپرمارکتی"),
        ("13", "اسباب بازی، کودک و نوزاد"),
        ("14", "ابزار آلات و تجهیزات"),
        ("15", "خودرو و موتورسیکلت"),
        ("16", "محصولات بومی و محلی"),
        ("17", "دیگر")
    ]
    name = models.CharField(max_length=100, verbose_name='نام شرکت')
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICE, verbose_name='دسته بندی کسب و کار')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='اکانت')
    phone_number = models.CharField(max_length=11, validators=[validate_numeric], verbose_name='شماره تلفن')
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت اطلاعات')
    updated = models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی اطلاعات')
    
    class Meta:
        verbose_name = 'شرکت'
        verbose_name_plural = 'شرکت‌ها'
    
    def __str__(self):
        return self.name
    
    def get_user_username(self):
        return self.user.username
    get_user_username.short_description = 'نام کاربری'
    
    def get_user_email(self):
        return self.user.email
    get_user_email.short_description = 'ایمیل'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Company

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'نام کاربری'
        self.fields['password1'].label = 'رمز عبور'
        self.fields['password2'].label = 'تکرار رمز عبور'


class CompanyRegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = Company
        fields = ['name', 'category', 'phone_number', 'email']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = 'نام شرکت'
        self.fields['category'].label = 'دسته بندی کسب و کار'
        self.fields['phone_number'].label = 'شماره تلفن'
        self.fields['email'].label = 'ایمیل'


class CompanyUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Company
        fields = ['name', 'category', 'email', 'phone_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = 'نام شرکت'
        self.fields['category'].label = 'دسته بندی کسب و کار'
        self.fields['email'].label = 'ایمیل'
        self.fields['phone_number'].label = 'شماره تلفن'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegisterForm, CompanyRegisterForm, CompanyUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout as logout_utils
from .models import Company
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
def company_register(request):
    if request.method == 'POST':
        company_register_form = UserRegisterForm(request.POST)
        if company_register_form.is_valid():
            user = company_register_form.save()
            login(request, user)
            messages.success(request, 'حساب کاربری شرکت با موفقیت ساخته شد.', 'success')
            return redirect('accounts:company_register_information')
    else:
        company_register_form = UserRegisterForm()
        context = {
            'company_register_form': company_register_form,
        }
    return render(request, 'accounts/company_register.html', context)


@login_required
def company_register_information(request):
    if request.method == 'POST':
        company_register_information_form = CompanyRegisterForm(request.POST)
        if company_register_information_form.is_valid():
            company = company_register_information_form.save(commit=False)
            company.user = request.user
            request.user.email = company_register_information_form.cleaned_data.get('email')
            request.user.save()
            company.save()
            messages.success(request, 'اطلاعات کاربری شرکت با موفقیت ثبت شد.', 'success')
            return redirect('accounts:profile')
    else:
        company_register_information_form = CompanyRegisterForm()
        context = {
            'company_register_information_form': company_register_information_form,
        }
    return render(request, 'accounts/company_register_information.html', context)


def login(request):
    if request.method == 'POST':
        authentication_form = AuthenticationForm(request, data=request.POST)
        if authentication_form.is_valid():
            username = authentication_form.cleaned_data.get('username')
            password = authentication_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'کاربر با موفقیت وارد شد.', 'success')
                company = get_object_or_404(Company, user=user)
                return redirect('accounts:profile', company_id=company.id)
            else:
                messages.error(request, 'نام کاربری یا رمز عبور اشتباه است.', 'error')
    else:
        authentication_form = AuthenticationForm()
        context = {
            'authentication_form': authentication_form,
        }
    return render(request, 'accounts/login.html', context)


def profile(request, company_id):
    company = get_object_or_404(Company, id=company_id)
    context = {
        'company': company,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def update_company(request, company_id):
    company = get_object_or_404(Company, id=company_id)
    if request.method == 'POST':
        company_update_form = CompanyUpdateForm(request.POST, instance=company)
        if company_update_form.is_valid():
            company = company_update_form.save(commit=False)
            request.user.email = company_update_form.cleaned_data.get('email')
            request.user.save()
            company.save()
            messages.success(request, 'اطلاعات شرکت با موفقیت بروزرسانی شد.', 'success')
            return redirect('accounts:profile', company_id=company.id)
    else:
        company_update_form = CompanyUpdateForm(instance=company)        
        context = {
            'company_update_form': company_update_form,
        }
    return render(request, 'accounts/company_update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'رمز عبور شما با موفقیت تغییر یافت.', 'success')
            return redirect('accounts:profile', company_id=request.user.company.id)
    else:
        password_change_form = PasswordChangeForm(request.user)
        context = {
            'password_change_form': password_change_form,
        }
    return render(request, 'accounts/change_password.html', context)


def logout(request, company_id):
    company = get_object_or_404(Company, id=company_id)
    context = {
        'company': company,
    }
    if request.method == 'POST':
        logout_utils(request)
        messages.success(request, 'کاربر با موفقیت خارج شد.', 'success')
        return redirect('home')
    return render(request, 'accounts/logout.html', context)


@login_required
def delete_account(request, company_id):
    company = get_object_or_404(Company, id=company_id)
    context = {
        'company': company,
    }
    if request.method == 'POST':
        user = company.user
        company.delete()
        user.delete()
        messages.success(request, 'حساب کاربری شما با موفقیت حذف شد.', 'success')
        return redirect('home')
    return render(request, 'accounts/delete_account.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h2>تغییر رمز عبور</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="تغییر رمز عبور"></input>
    </form>
    <a href="{% url 'accounts:profile' request.user.company.id %}" class="btn btn-secondary">لغو</a>
{% endblock %}

accounts/templates/accounts/company_register.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h2>ثبت اطلاعات شرکت</h2>
    <form method="post">
        {% csrf_token %}
        {{ company_register_form.as_p }}
        <input type="submit" value="ثبت اطلاعات"></input>
    </form>
{% endblock %}

accounts/templates/accounts/company_register_information.html
{% extends "base.html" %}

{% block content %}
    <h2>ثبت نام شرکت</h2>
    <form method="post">
        {% csrf_token %}
        {{ company_register_information_form.as_p }}
        <input type="submit" value="ثبت نام"></input>
    </form>
{% endblock %}

accounts/templates/accounts/delete_account.html
{% extends 'base.html' %}

{% block content %}
    <h2>حذف حساب کاربری</h2>
    <p>آیا مطمئن هستید که می‌خواهید حساب کاربری خود را حذف کنید؟ این عمل غیرقابل بازگشت است.</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="حذف حساب کاربری"></input>
    </form>
    <a href="{% url 'accounts:profile' company.id %}">لغو</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h2>ورود به سیستم</h2>
    <form method="post">
        {% csrf_token %}
        {{ authentication_form.as_p }}
        <input type="submit" value="ورود"></input>
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>آیا مطمئن هستید که می‌خواهید از حساب کاربری خارج شوید؟</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="بله، حذف شود"></input>
    </form>
    <a href="{% url 'accounts:profile' company.id %}">لغو</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h2>اطلاعات شرکت</h2>
    <a href="{% url "accounts:update_company" company.id %}">ویرایش اطلاعات شرکت</a>
    <a href="{% url "accounts:delete_account" company.id %}">حذف حساب کاربری</a>
    <a href="{% url "accounts:logout" company.id %}">خروج از حساب کاربری</a>
    <p><strong>نام شرکت:</strong> {{ company.name }}</p>
    <p><strong>دسته بندی کسب و کار:</strong> {{ company.category }}</p>
    <p><strong>نام کاربری صاحب شرکت:</strong> {{ company.get_user_username }}</p>
    <p><strong>ایمیل صاحب شرکت:</strong> {{ company.get_user_email }}</p>
    <p><strong>شماره تلفن:</strong> {{ company.phone_number }}</p>
    <hr>
    <p><strong>زمان ثبت اطلاعات:</strong> {{ company.created }}</p>
    <p><strong>زمان آخرین بروزرسانی اطلاعات:</strong> {{ company.updated }}</p>
{% endblock %}

accounts/templates/accounts/update_company.html
{% extends 'base.html' %}

{% block content %}
    <h2>ویرایش اطلاعات شرکت</h2>
    <a href="{% url "accounts:delete_account" %}">تغییر رمز عبور</a>
    <form method="post">
        {% csrf_token %}
        {{ company_update_form.as_p }}
        <input type="submit" value="ذخیره تغییرات">
    </form>
    <a href="{% url 'accounts:profile' company.id %}">لغو</a>
{% endblock %}