config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls")),
    path('warehouse/', include("warehouse.urls")),
    path('supplier/', include("supplier.urls")),
    path('purchaseinvoice/', include("purchaseinvoice.urls")),
    path('product/', include("product.urls")),
    path('salesinvoice/', include("salesinvoice.urls")),
    path('customer/', include("customer.urls")),
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'
urlpatterns = [
    path('', home, name='home'),
]

product/urls.py
from django.urls import path
from .views import product_list, product_detail, add_product, update_product, delete_product

app_name = 'product'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('detail/<int:product_id>/', product_detail, name='product_detail'),
    path('add/', add_product, name='add_product'),
    path('update/<int:product_id>/', update_product, name='update_product'),
    path('delete/<int:product_id>/', delete_product, name='delete_product'),
]

product/models.py
from django.db import models
from warehouse.models import Warehouse
from shared.utils import jalali_converter_date_time

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='نام محصول')
    price = models.DecimalField(max_digits=12, decimal_places=0, default=0, verbose_name='قیمت')
    warehouse = models.ManyToManyField(Warehouse, through='Inventory')
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت اطلاعات')
    updated = models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی اطلاعات')
    
    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.name
    
    def get_jalali_created(self):
        return jalali_converter_date_time(self.created)
    get_jalali_created.short_description = 'زمان ثبت اطلاعات'

    def get_jalali_updated(self):
        return jalali_converter_date_time(self.updated)
    get_jalali_updated.short_description = 'زمان آخرین بروزرسانی اطلاعات'


class Inventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, verbose_name='انبار')
    quantity = models.PositiveIntegerField(default=1, verbose_name='تعداد')

    class Meta:
        unique_together = ('product', 'warehouse')
        verbose_name = 'موجودی'
        verbose_name_plural = 'موجودی‌ها'

    def __str__(self):
        return f"{self.product.name} در {self.warehouse.branch}: {self.quantity}"

product/forms.py
from django import forms
from .models import Product, Inventory
from warehouse.models import Warehouse
from django.forms import inlineformset_factory


class ProductAddForm(forms.ModelForm):
    quantity = forms.IntegerField(label='تعداد')
    warehouse = forms.ModelChoiceField(queryset=Warehouse.objects.all(), label='شعبه انبار')

    class Meta:
        model = Product
        fields = ('name', 'price')

    def save(self):
        product = super().save()
        warehouse = self.cleaned_data.get('warehouse')
        quantity = self.cleaned_data.get('quantity')
        if warehouse and quantity:
            Inventory.objects.create(product=product, warehouse=warehouse, quantity=quantity)
        return product
    

class ProductUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ('name', 'price')
    

class InventoryUpdateForm(forms.ModelForm):
     
    class Meta:
        model = Inventory
        fields = ('quantity', 'warehouse')
        

InventoryFormSet = inlineformset_factory(Product, Inventory, form=InventoryUpdateForm, extra=1, can_delete=True)

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Inventory
from django.contrib import messages
from .forms import ProductAddForm, ProductUpdateForm, InventoryFormSet

# Create your views here.
def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'product/product_list.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    inventory = Inventory.objects.filter(product=product)
    context = {
        'product': product,
        'inventory': inventory,   
    }
    return render(request, 'product/product_detail.html', context)


def add_product(request):
    if request.method == 'POST':
        product_add_form = ProductAddForm(request.POST)
        if product_add_form.is_valid():
            product_add_form.save()
            messages.success(request, 'محصول جدید با موفقیت اصافه شد.', 'success')
            return redirect('product:product_list')
        else:
            context = {
                'product_add_form': product_add_form,
            }
    else:
        product_add_form = ProductAddForm()
        context = {
            'product_add_form': product_add_form,
        }
    return render(request, 'product/add_product.html', context)


def update_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        product_update_form = ProductUpdateForm(request.POST, instance=product)
        inventory_form = InventoryFormSet(request.POST, instance=product)
        if product_update_form.is_valid() and inventory_form.is_valid():
            product_update_form.save()
            inventory_form.save()
            messages.success(request, 'اطلاعات محصول با موفقیت بروزرسانی شد.', 'success')
            return redirect('product:product_detail', product_id)
    else:
        product_update_form = ProductUpdateForm(instance=product)
        inventory_form = InventoryFormSet(instance=product)
        context = {
            'product': product,
            'product_update_form': product_update_form,
            'inventory_form': inventory_form,
        }          
    return render(request, 'product/update_product.html', context)


def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    context = {
        'product': product,
    }
    if request.method == 'POST':
        product.delete()
        messages.success(request, 'محصول با موفقیت حذف شد.', 'success')
        return redirect('product:product_list')
    return render(request, 'product/confirm_delete_product.html', context)

product/templates/product/add_product.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>اضافه کردن محصول جدید</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ product_add_form.as_p }}
        <input type="submit" value="اضافه کردن">
    </form>
    <a href="{% url 'product:product_list' %}">لغو</a>
{% endblock %}

product/templates/product/confirm_delete_product.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>آیا مطمئن هستید که می‌خواهید محصول "{{ product.name }}" را حذف کنید؟</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="بله، حذف شود"></input>
    </form>
    <a href="{% url 'product:product_detail' product.id %}">لغو</a>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>اطلاعات محصول</h1>
    <a href="{% url "product:update_product" product.id %}">ویرایش محصول</a>
    <a href="{% url "product:delete_product" product.id %}">حذف</a>
    <p><strong>نام:</strong> {{ product.name }}</p>
    <p><strong>قیمت:</strong> {{ product.price }} تومان</p>
    <h3>موجودی در انبارها</h3>
    <table>
        <tr>
            <th>انبار</th>
            <th>موجودی</th>
        </tr>
        {% for item in inventory %}
            <tr>
                <td>{{ item.warehouse.branch }}</td>
                <td>{{ item.quantity }}</td>
            </tr>
        {% endfor %}
    </table>
    <hr>
    <p><strong>زمان ثبت اطلاعات:</strong> {{ product.get_jalali_created }}</p>
    <p><strong>زمان آخرین بروزرسانی اطلاعات:</strong> {{ product.get_jalali_updated }}</p>
{% endblock %}

product/templates/product/product_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>لیست محصولات</h1>
    <a href="{% url 'product:add_product' %}">اضافه کردن محصول جدید</a>
    <ul>
        {% for product in products %}
            <li>
                <a href="{% url 'product:product_detail' product.id %}">{{ product.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

product/templates/product/update_product.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>ویرایش محصول: {{ product.name }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ product_update_form.as_p }}
        {{ inventory_form.management_form }}
        <h3>موجودی در انبارها</h3>
        {% for form in inventory_form %}
            {{ form.as_p }}
        {% endfor %}
        <input type="submit" value="ذخیره تغییرات">
    </form>
    <a href="{% url 'product:product_detail' product.id %}">لغو</a>
{% endblock %}