config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls")),
    path('warehouse/', include("warehouse.urls")),
    path('supplier/', include("supplier.urls")),
    path('purchaseinvoice/', include("purchaseinvoice.urls")),
    path('product/', include("product.urls")),
    path('salesinvoice/', include("salesinvoice.urls")),
    path('customer/', include("customer.urls")),
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'
urlpatterns = [
    path('', home, name='home'),
]

supplier/urls.py
from django.urls import path
from .views import supplier_list, supplier_detail, add_supplier, update_supplier, delete_supplier

app_name = 'supplier'
urlpatterns = [
    path('', supplier_list, name='supplier_list'),
    path('detail/<int:supplier_id>/', supplier_detail, name='supplier_detail'),
    path('add/', add_supplier, name='add_supplier'),
    path('update/<int:supplier_id>/', update_supplier, name='update_supplier'),
    path('delete/<int:supplier_id>/', delete_supplier, name='delete_supplier'),
]

supplier/models.py
from django.db import models
from shared.utils import jalali_converter_date_time
from shared.validators import validate_numeric

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="نام تامین کننده")
    location = models.TextField(unique=True, blank=True, null=True, verbose_name="آدرس")
    website = models.URLField(unique=True, blank=True, null=True, verbose_name="وبسایت")
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت اطلاعات')
    updated = models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی اطلاعات')

    class Meta:
        verbose_name = "تامین کننده"
        verbose_name_plural = "تامین کننده‌ها"

    def __str__(self):
        return self.name
    
    def get_jalali_created(self):
        return jalali_converter_date_time(self.created)
    get_jalali_created.short_description = 'زمان ثبت اطلاعات'

    def get_jalali_updated(self):
        return jalali_converter_date_time(self.updated)
    get_jalali_updated.short_description = 'زمان آخرین بروزرسانی اطلاعات'
    

class PhoneNumber(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, verbose_name='انبار')
    phone_number = models.CharField(max_length=11, unique=True, blank=True, null=True, validators=[validate_numeric], verbose_name='شماره تلفن')
    
    class Meta:
        verbose_name = 'شماره تلفن'
        verbose_name_plural = 'شماره تلفن‌ها'

    def __str__(self):
        return str(self.phone_number)

supplier/forms.py
from django import forms
from .models import Supplier, PhoneNumber
from shared.validators import validate_numeric
from django.forms import inlineformset_factory


class SupplierAddForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=11, required=False, label='شماره تلفن', validators=[validate_numeric])
    
    class Meta:
        model = Supplier
        fields = ('name', 'location', 'website')

    def save(self):
        supplier = super().save()
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number:
            PhoneNumber.objects.create(supplier=supplier, phone_number=phone_number)
        return supplier
    
    
class SupplierUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Supplier
        fields = ('name', 'location', 'website')


class PhoneNumberUpdateForm(forms.ModelForm):
    
    class Meta:
        model = PhoneNumber
        fields = ('phone_number',)
        
        
PhoneNumberFormSet = inlineformset_factory(Supplier, PhoneNumber, form=PhoneNumberUpdateForm, extra=1, can_delete=True)

supplier/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Supplier, PhoneNumber
from django.contrib import messages
from .forms import SupplierAddForm, SupplierUpdateForm, PhoneNumberFormSet

# Create your views here.
def supplier_list(request):
    suppliers = Supplier.objects.all()
    context = {
        'suppliers': suppliers,
    }
    return render(request, 'supplier/supplier_list.html', context)


def supplier_detail(request, supplier_id):
    supplier = get_object_or_404(Supplier, id=supplier_id)
    phone_numbers = PhoneNumber.objects.filter(supplier=supplier)
    context = {
        'supplier': supplier,
        'phone_numbers': phone_numbers,
    }
    return render(request, 'supplier/supplier_detail.html', context)


def add_supplier(request):
    if request.method == 'POST':
        supplier_add_form = SupplierAddForm(request.POST)
        if supplier_add_form.is_valid():
            supplier_add_form.save()
            messages.success(request, 'تأمین کننده جدید با موفقیت اصافه شد.', 'success')
            return redirect('supplier:supplier_list')
    else:
        supplier_add_form = SupplierAddForm()
        context = {
            'supplier_add_form': supplier_add_form,
        }
    return render(request, 'supplier/add_supplier.html', context)


def update_supplier(request, supplier_id):
    supplier = get_object_or_404(Supplier, id=supplier_id)
    if request.method == 'POST':
        supplier_update_form = SupplierUpdateForm(request.POST, instance=supplier)
        phone_numbers_form = PhoneNumberFormSet(request.POST, instance=supplier)
        if supplier_update_form.is_valid() and phone_numbers_form.is_valid():
            supplier_update_form.save()
            phone_numbers_form.save()
            messages.success(request, 'اطلاعات تأمین کننده با موفقیت بروزرسانی شد.', 'success')
            return redirect('supplier:supplier_detail', supplier_id)
    else:
        supplier_update_form = SupplierUpdateForm(instance=supplier)
        phone_numbers_form = PhoneNumberFormSet(instance=supplier)
        context = {
            'supplier': supplier,
            'supplier_update_form': supplier_update_form,
            'phone_numbers_form': phone_numbers_form,
        }          
    return render(request, 'supplier/update_supplier.html', context)


def delete_supplier(request, supplier_id):
    supplier = get_object_or_404(Supplier, id=supplier_id)
    context = {
        'supplier': supplier
    }
    if request.method == 'POST':
        supplier.delete()
        messages.success(request, 'تأمین کننده با موفقیت حذف شد.', 'success')
        return redirect('supplier:supplier_list')
    return render(request, 'supplier/confirm_delete_supplier.html', context)

supplier/templates/supplier/add_supplier.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>اضافه کردن تأمین کننده جدید</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ supplier_add_form.as_p }}
        <input type="submit" value="اضافه کردن">
    </form>
    <a href="{% url 'supplier:supplier_list' %}">لغو</a>
{% endblock %}

supplier/templates/supplier/confirm_delete_supplier.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>آیا مطمئن هستید که می‌خواهید تأمین کننده "{{ supplier.name }}" را حذف کنید؟</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="بله، حذف شود"></input>
    </form>
    <a href="{% url 'supplier:supplier_detail' supplier.id %}">لغو</a>
{% endblock %}

supplier/templates/supplier/supplier_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>اطلاعات تأمین کننده</h1>
    <a href="{% url "supplier:update_supplier" supplier.id %}">ویرایش تأمین کننده</a>
    <a href="{% url "supplier:delete_supplier" supplier.id %}">حذف</a>
    <p><strong>نام:</strong> {{ supplier.name }}</p>
    <p><strong>آدرس:</strong> {{ supplier.location }}</p>
    <p><strong>وبسایت:</strong> {{ supplier.website }}</p>
    <h3>شماره تلفن‌ها</h3>
    <ul>
        {% for phone_number in phone_numbers %}
            <li>{{ phone_number.phone_number }}</li>
        {% empty %}
            <li>شماره تلفنی ثبت نشده است.</li>
        {% endfor %}
    </ul>
    <hr>
    <p><strong>زمان ثبت اطلاعات:</strong> {{ supplier.get_jalali_created }}</p>
    <p><strong>زمان آخرین بروزرسانی اطلاعات:</strong> {{ supplier.get_jalali_updated }}</p>
{% endblock %}

supplier/templates/supplier/supplier_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>لیست تأمین کنندگان</h1>
    <a href="{% url 'supplier:add_supplier' %}">اضافه کردن تأمین کننده جدید</a>
    <ul>
        {% for supplier in suppliers %}
            <li>
                <a href="{% url 'supplier:supplier_detail' supplier.id %}">{{ supplier.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

supplier/templates/supplier/update_supplier.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>ویرایش تأمین کننده: {{ supplier.name }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ supplier_update_form.as_p }}
        {{ phone_numbers_form.management_form }}
        <h3>شماره تلفن‌ها</h3>
        {% for form in phone_numbers_form %}
            {{ form.as_p }}
        {% endfor %}
        <input type="submit" value="ذخیره تغییرات">
    </form>
    <a href="{% url 'supplier:supplier_detail' supplier.id %}">لغو</a>
{% endblock %}