config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls")),
    path('warehouse/', include("warehouse.urls")),
    path('supplier/', include("supplier.urls")),
    path('purchaseinvoice/', include("purchaseinvoice.urls")),
    path('product/', include("product.urls")),
    path('salesinvoice/', include("salesinvoice.urls")),
    path('customer/', include("customer.urls")),
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'
urlpatterns = [
    path('', home, name='home'),
]

warehouse/urls.py
from django.urls import path
from .views import warehouse_list, warehouse_detail, add_warehouse, update_warehouse, delete_warehouse

app_name = 'warehouse'
urlpatterns = [
    path('', warehouse_list, name='warehouse_list'),
    path('detail/<int:warehouse_id>/', warehouse_detail, name='warehouse_detail'),
    path('add/', add_warehouse, name='add_warehouse'),
    path('update/<int:warehouse_id>/', update_warehouse, name='update_warehouse'),
    path('delete/<int:warehouse_id>/', delete_warehouse, name='delete_warehouse'),
]

warehouse/models.py
from django.db import models
from shared.utils import jalali_converter_date_time
from shared.validators import validate_numeric

# Create your models here.
class Warehouse(models.Model):
    branch = models.CharField(max_length=100, unique=True, verbose_name='شعبه انبار')
    location = models.TextField(blank=True, null=True, verbose_name='آدرس')
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت اطلاعات')
    updated = models.DateTimeField(auto_now=True, verbose_name='زمان آخرین بروزرسانی اطلاعات')
    
    class Meta:
        verbose_name = 'انبار'
        verbose_name_plural = 'انبارها'

    def __str__(self):
        return self.branch
        
    def get_jalali_created(self):
        return jalali_converter_date_time(self.created)
    get_jalali_created.short_description = 'زمان ثبت اطلاعات'

    def get_jalali_updated(self):
        return jalali_converter_date_time(self.updated)
    get_jalali_updated.short_description = 'زمان آخرین بروزرسانی اطلاعات'


class PhoneNumber(models.Model):
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, verbose_name='انبار')
    phone_number = models.CharField(max_length=11, unique=True, blank=True, null=True, validators=[validate_numeric], verbose_name='شماره تلفن')

    class Meta:
        verbose_name = 'شماره تلفن'
        verbose_name_plural = 'شماره تلفن‌ها'

    def __str__(self):
        return str(self.phone_number)

warehouse/forms.py
from django import forms
from .models import Warehouse, PhoneNumber
from shared.validators import validate_numeric
from django.forms import inlineformset_factory


class WarehouseAddForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=11, required=False, validators=[validate_numeric], label='شماره تلفن')
    
    class Meta:
        model = Warehouse
        fields = ('branch', 'location')

    def save(self):
        warehouse = super().save()
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number:
            PhoneNumber.objects.create(warehouse=warehouse, phone_number=phone_number)
        return warehouse


class WarehouseUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Warehouse
        fields = ('branch', 'location')


class PhoneNumberUpdateForm(forms.ModelForm):
    
    class Meta:
        model = PhoneNumber
        fields = ('phone_number',)
        
        
PhoneNumberFormSet = inlineformset_factory(Warehouse, PhoneNumber, form=PhoneNumberUpdateForm, extra=1, can_delete=True)

warehouse/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Warehouse, PhoneNumber
from django.contrib import messages
from .forms import WarehouseAddForm, WarehouseUpdateForm, PhoneNumberFormSet

# Create your views here.
def warehouse_list(request):
    warehouses = Warehouse.objects.all()
    context = {
        'warehouses': warehouses,
    }
    return render(request, 'warehouse/warehouse_list.html', context)


def warehouse_detail(request, warehouse_id):
    warehouse = get_object_or_404(Warehouse, id=warehouse_id)
    phone_numbers = PhoneNumber.objects.filter(warehouse=warehouse)
    context = {
        'warehouse': warehouse,
        'phone_numbers': phone_numbers,
    }
    return render(request, 'warehouse/warehouse_detail.html', context)


def add_warehouse(request):
    if request.method == 'POST':
        warehouse_add_form = WarehouseAddForm(request.POST)
        if warehouse_add_form.is_valid():
            warehouse_add_form.save()
            messages.success(request, 'انبار جدید با موفقیت اصافه شد.', 'success')
            return redirect('warehouse:warehouse_list')
    else:
        warehouse_add_form = WarehouseAddForm()
        context = {
            'warehouse_add_form': warehouse_add_form,
        }
    return render(request, 'warehouse/add_warehouse.html', context)


def update_warehouse(request, warehouse_id):
    warehouse = get_object_or_404(Warehouse, id=warehouse_id)
    if request.method == 'POST':
        warehouse_update_form = WarehouseUpdateForm(request.POST, instance=warehouse)
        phone_numbers_form = PhoneNumberFormSet(request.POST, instance=warehouse)
        if warehouse_update_form.is_valid() and phone_numbers_form.is_valid():
            warehouse_update_form.save()
            phone_numbers_form.save()
            messages.success(request, 'اطلاعات انبار با موفقیت بروزرسانی شد.', 'success')
            return redirect('warehouse:warehouse_detail', warehouse_id)
    else:
        warehouse_update_form = WarehouseUpdateForm(instance=warehouse)
        phone_numbers_form = PhoneNumberFormSet(instance=warehouse)
        context = {
            'warehouse': warehouse,
            'warehouse_update_form': warehouse_update_form,
            'phone_numbers_form': phone_numbers_form,
        }          
    return render(request, 'warehouse/update_warehouse.html', context)


def delete_warehouse(request, warehouse_id):
    warehouse = get_object_or_404(Warehouse, id=warehouse_id)
    context ={
        'warehouse': warehouse,
    }
    if request.method == 'POST':
        warehouse.delete()
        messages.success(request, 'انبار با موفقیت حذف شد.', 'success')
        return redirect('warehouse:warehouse_list')
    return render(request, 'warehouse/confirm_delete_warehouse.html', context)

warehouse/templates/warehouse/add_warehouse.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>اضافه کردن انبار جدید</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ warehouse_add_form.as_p }}
        <input type="submit" value="اضافه کردن">
    </form>
    <a href="{% url 'warehouse:warehouse_list' %}">لغو</a>
{% endblock %}

warehouse/templates/warehouse/confirm_delete_warehouse.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>آیا مطمئن هستید که می‌خواهید انبار "{{ warehouse.branch }}" را حذف کنید؟</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="بله، حذف شود"></input>
    </form>
    <a href="{% url 'warehouse:warehouse_detail' warehouse.id %}">لغو</a>
{% endblock %}

warehouse/templates/warehouse/update_warehouse.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>ویرایش انبار: {{ warehouse.branch }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ warehouse_update_form.as_p }}
        {{ phone_numbers_form.management_form }}
        <h3>شماره تلفن‌ها</h3>
        {% for form in phone_numbers_form %}
            {{ form.as_p }}
        {% endfor %}
        <input type="submit" value="ذخیره تغییرات">
    </form>
    <a href="{% url 'warehouse:warehouse_detail' warehouse.id %}">لغو</a>
{% endblock %}

warehouse/templates/warehouse/warehouse_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>اطلاعات انبار</h1>
    <a href="{% url "warehouse:update_warehouse" warehouse.id %}">ویرایش انبار</a>
    <a href="{% url "warehouse:delete_warehouse" warehouse.id %}">حذف</a>
    <p><strong>شعبه:</strong> {{ warehouse.branch }}</p>
    <p><strong>آدرس:</strong> {{ warehouse.location }}</p>
    <h3>شماره تلفن‌ها</h3>
    <ul>
        {% for phone_number in phone_numbers %}
            <li>{{ phone_number.phone_number }}</li>
        {% empty %}
            <li>شماره تلفنی ثبت نشده است.</li>
        {% endfor %}
    </ul>
    <hr>
    <p><strong>زمان ثبت اطلاعات:</strong> {{ warehouse.get_jalali_created }}</p>
    <p><strong>زمان آخرین بروزرسانی اطلاعات:</strong> {{ warehouse.get_jalali_updated }}</p>
{% endblock %}

warehouse/templates/warehouse/warehouse_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>لیست انبارها</h1>
    <a href="{% url 'warehouse:add_warehouse' %}">اضافه کردن انبار جدید</a>
    <ul>
        {% for warehouse in warehouses %}
            <li>
                <a href="{% url 'warehouse:warehouse_detail' warehouse.id %}">{{ warehouse.branch }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}